# Generated by Django 2.0.2 on 2018-02-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='flat_number',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
