# Generated by Django 2.0.2 on 2018-02-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_auto_20180227_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='email_type',
            field=models.SmallIntegerField(choices=[(1, 'Home'), (2, 'Business'), (3, 'Other')]),
        ),
    ]
