# Generated by Django 2.0.2 on 2018-02-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_auto_20180227_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('members', models.ManyToManyField(to='storage.Person')),
            ],
        ),
        migrations.AlterField(
            model_name='phone',
            name='number',
            field=models.BigIntegerField(),
        ),
    ]
