# Generated by Django 2.0.2 on 2018-04-17 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0007_group_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='description',
            field=models.TextField(null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=64, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=64, verbose_name=''),
        ),
    ]
